import { type Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Analytics } from '@vercel/analytics/react';
import { Geist, Geist_Mono } from 'next/font/google';
import Nav from './components/Nav';
import Footer from './components/Footer';
import AOSInit from './components/AOSInit';
import './globals.css';
import './styles/bootstrap.min.css';
import './styles/bootstrap-grid.min.css';
import './styles/bootstrap-reboot.min.css';
import './styles/animate.css';
import './styles/magnific-popup.css';
import './styles/jquery.countdown.css';
// Import font CSS files before style.css
import './styles/fonts/font-awesome/css/font-awesome.css';
import './styles/fonts/elegant_font/HTML_CSS/style.css';
import './styles/fonts/et-line-font/style.css';
import './styles/style.css';
import './styles/colors/scheme-01.css';
import './styles/coloring.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <AOSInit />
          <Nav />
          {children}
          <Footer />
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}

