import { type Metadata } from 'next';
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import Nav from './components/Nav';
import Footer from './components/Footer';
import AOSInit from './components/AOSInit';
import './globals.css';
import './styles/bootstrap.min.css';
import './styles/bootstrap-grid.min.css';
import './styles/bootstrap-reboot.min.css';
import './styles/animate.css';
import './styles/magnific-popup.css';
import './styles/jquery.countdown.css';
// Import font CSS files before style.css
import './styles/fonts/font-awesome/css/font-awesome.css';
import './styles/fonts/elegant_font/HTML_CSS/style.css';
import './styles/fonts/et-line-font/style.css';
import './styles/style.css';
import './styles/colors/scheme-01.css';
import './styles/coloring.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <AOSInit />
          <Nav />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}

